services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../laravel_docker_basic:/var/www/html
    networks:
      - default
    links: 
        - mysql
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../laravel_docker_basic:/var/www/html
    networks:
      - default
    links: 
        - mysql
  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: "Hoang123"
      MYSQL_USER: "Hoang"
      MYSQL_DATABASE: "laravel_basic"
      MYSQL_PASSWORD: "Hoang123"
networks:
  default: